"""LAS 58 EXPLICADAS: que es cada combinacion de la ficha 58 y como se pide en lineas de los nexos.

Las escribe el diseno a partir de las 58, no de los casos del banco: la segunda llamada del camino de
numeros recibe SOLO las de los numeros que eligio la primera.
"""
G = {
    1: "Nombra un producto. Linea: producto | <id P del ESTADO, o el nombre con color>. La ficha trae precio, stock y datos.",
    2: "Pide un rubro. Linea: buscar | <rubro> | <cuantos, 6 si no dice> | nada | nada.",
    3: "Pregunta un dato de un producto. Linea: producto | <id P o nombre>. Si la ficha no lo trae, el codigo lo dice: no lo inventes.",
    4: "Da por cierto algo de un producto. Linea: producto | <id P o nombre>, para que el codigo verifique; no lo aceptes de palabra.",
    5: "Exige una caracteristica. Linea: buscar | <rubro> | <cuantos> | nada | <la condicion: capacidad, conexion, color, 'hasta N pesos' si pone un tope>.",
    6: "Prefiere algo sin exigirlo. Linea: buscar | <rubro> | <cuantos> | nada | preferentemente <X>.",
    7: "Rechaza una marca o algo. Linea: buscar con condicion 'que no sea X'. El codigo lo guarda como filtro vivo.",
    8: "Pide lo menos posible de algo, por ejemplo lo menos chino. Linea: buscar con condicion 'origen no chino' o la que corresponda.",
    9: "Ordena: el mas barato, el mas caro, el mas liviano. Linea: buscar | <rubro, o 'toda la tienda' si no nombra rubro> | <cuantos> | <mas barato, mas caro o mas liviano> | nada. 'De acuerdo a la crisis' o 'economico' es mas barato.",
    10: "Pregunta por el envio a un lugar. Linea: envio | <destino>, una por destino.",
    11: "Pregunta una regla de la tienda: pagos, cuotas, factura, garantia, retiro, horarios, envios al exterior. Linea: politica | <tema>.",
    12: "Da por cierta una regla de la tienda. Linea: politica | <tema>, para verificar; nunca la confirmes de palabra.",
    13: "Habla de si mismo para pedir algo: revendedor, por cantidad, mayorista. Linea: politica | mayoristas o promociones.",
    14: "Pregunta saber general de tecnologia. Linea: nada; lo explica el que redacta.",
    15: "Compra. Linea: agregar | <id P o D<k>> | <cantidad> | <destino o nada>.",
    16: "Reparte el pago entre medios. Linea: pago | <medio porcentaje, medio porcentaje>. Si dice un solo medio, 'transferencia 100'.",
    17: "Varios productos con distinto pedido. Una linea por producto, cada una con su forma.",
    18: "Productos y envio. Una linea por producto y una linea envio por destino.",
    19: "Producto y regla de la tienda. Una linea producto y una linea politica.",
    20: "Suma varios productos. Un agregar por producto con su cantidad, y cuenta.",
    21: "Suma y reparte el pago. Agregar lo que falte, cuenta y pago.",
    22: "Producto y saber general. Linea producto; el saber general lo explica el que redacta.",
    23: "Una condicion para una sola parte. La condicion va solo en la linea de esa parte.",
    24: "Una condicion para todas las partes: 'los dos negros', 'todos los mas baratos'. Se repite en cada linea buscar.",
    25: "Cantidad distinta por producto. Un agregar por producto con su cantidad, y cuenta.",
    26: "Destino distinto por producto o por unidad. Un agregar POR CADA DESTINO con la cantidad de ese destino: 'quiero dos, uno a A y otro a B' son dos lineas agregar de 1, nunca cantidad 2 y despues cambiar el destino. Las cantidades por destino suman lo pedido.",
    27: "Ordena dentro de lo que ya le mostraron: 'de esos, el mas barato'. NO se busca: elegi del ULTIMO LISTADO del ESTADO y escribi su id P.",
    28: "Si no hay una cosa, otra. Linea producto de las dos y decidir | <la condicion>; la compra va en la segunda vuelta.",
    29: "Si un dato da si, compra. Linea compatibilidad o producto para averiguar el dato, y decidir | <la condicion>. La compra, con agregar, va en la segunda vuelta.",
    30: "Si el cruce da no, una alternativa. Linea compatibilidad, decidir, y en la segunda vuelta buscar la alternativa.",
    31: "Si el total pasa un monto, quita algo. Agregar todo, cuenta y decidir | <si pasa de N, sacar X>.",
    32: "Compara dos y elige. Linea producto de cada uno y decidir | <el criterio>; la compra en la segunda vuelta.",
    33: "Se corrige en el mismo mensaje: 'ah no, mejor'. Vale solo lo ultimo que dijo.",
    34: "Corrige algo de antes. Linea: cambiar | <id P> | destino <lugar>, cantidad <N> o variante <color>. 'Lo de Rosario' es cambiar | destino Rosario | destino <nuevo>. Sacar algo: sacar | <id P>.",
    35: "Cambia o suelta una condicion que valia. Linea: olvidar | <el filtro>, y buscar de nuevo.",
    36: "Pregunta si un producto anda con su equipo o con otro producto. Linea: compatibilidad | <id P o nombre> | <el equipo: mac, notebook, ps5, o el id P del otro producto>. Una por cada cruce.",
    37: "Pregunta que le sirve a su equipo dentro de un rubro. Linea: buscar | <rubro> | 6 | nada | compatible con <equipo>.",
    38: "Pregunta si algo le sirve sin decir su equipo. Linea: preguntar | que equipo o modelo tiene.",
    39: "Da por cierto un dato falso de un producto. Linea: producto | <id P>; el codigo dira lo real.",
    40: "Da por cierta una regla falsa de la tienda. Linea: politica | <tema>.",
    41: "Pide un permiso o descuento por quien es: jubilado, estudiante. Linea: politica | promociones.",
    42: "Pide condiciones que no se pueden dar juntas. Linea buscar con todas las condiciones; el codigo dira que no hay.",
    43: "'Ese', 'lo', 'el mismo': el ultimo producto nombrado en el ESTADO. Escribi su id P.",
    44: "'El otro': del ULTIMO LISTADO, el que no eligio. Escribi su id P.",
    45: "Modifica la busqueda anterior: 'y en blanco?'. Linea buscar del mismo rubro con la condicion nueva.",
    46: "Sigue buscando con lo que ya pidio: 'y alguno mecanico?'. Linea buscar con la condicion nueva; los filtros vivos los aplica el codigo.",
    47: "Usa un dato que dio antes, como su destino o su equipo. Tomalo del ESTADO o de los ultimos mensajes.",
    48: "Habla del pedido que ya armo. Lineas cambiar, sacar o cuenta sobre el PEDIDO VIGENTE; no lo vuelvas a agregar.",
    49: "Se refiere a algo de hace rato por un nombre parcial. Busca en PRODUCTOS NOMBRADOS el que coincide y escribi su id P.",
    50: "Contesta una repregunta: 'el primero'. Es por posicion en el ULTIMO LISTADO.",
    51: "Se refiere a otra parte del mismo mensaje: 'y mandame ese'. Usa D<k>, la linea de esa parte.",
    52: "Pide un total sin decir destino. Linea cuenta; si el destino hace falta y no esta en el ESTADO, preguntar.",
    53: "Usa la memoria con una condicion. Id P del ESTADO y decidir.",
    54: "Su equipo con una condicion y un orden: 'la mas potente que aguante mi fuente'. Linea buscar | <rubro> | 1 | mas caro | compatible con <equipo>.",
    55: "Corrige a cual se referia y compra. Linea agregar con el id P correcto; si ya habia otro en el pedido, sacar el anterior.",
    56: "Varias preguntas juntas. Una linea por cada parte, cada una con su forma.",
    57: "Algo fuera de la tienda. Linea: nada.",
    58: "Charla mezclada con un pedido. La charla no lleva linea; el pedido si.",
}
