name: Deploy a Cloud Run

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'tests/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1000939441597/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@memory-engine-v1.iam.gserviceaccount.com

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: memory-engine-v1

      - name: Deploy a Cloud Run
        run: |
          gcloud run deploy agente-bot \
            --region southamerica-east1 \
            --source . \
            --project memory-engine-v1 \
            --quiet
